name: site-briet 
on:
  push:
    branches: 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-macros-plugin mkdocs-mermaid2-plugin mkdocs-minify-plugin mkdocs-charts-plugin
      - run: mkdocs gh-deploy --force
